### ISSUE TITLE
Change in clean-urls behaviour

### ISSUE THREAD

**Issue by willfurnass** [cryogen-project/cryogen-core#115]
With `cryogen-core` 0.1.61 I had `clean-urls?` enabled and so Cryogen generated files/URLs such as 

[/resources/public/posts-output/2018-10-16-arch-block-devs/index.html](http://learningpatterns.me/resources/public/posts-output/2018-10-16-arch-block-devs/index.html)   
                         
After switching to 0.1.65 (following the merging of (#113) I can only generate files like the following (with `clean-urls?` still enabled):

`/resources/public/posts-output/2018-10-16-arch-block-devs.html` 

However URLS in the generated HTML files are inconsistently of the following form:

`/posts-output/2018-10-16-arch-block-devs`

Can we reenable the 0.1.61 behaviour?

FYI my `project.clj` contains:
```
            :dependencies [[org.clojure/clojure "1.9.0"]
                           [ring/ring-devel "1.6.3"]
                           [compojure "1.6.0"]
                           [ring-server "0.5.0"]
                           [cryogen-markdown "0.1.7"]
                           [cryogen-core "0.1.65"]]
            :plugins [[lein-ring "0.12.5"]]
            :main cryogen.core
            :ring {:init cryogen.server/init
                   :handler cryogen.server/handler})
```

**Comment by lacarmen** [comment]
Please take a look at #166. The change was done to prevent the additional redirect from `/foo` to `/foo/`. 

Navigating to `/posts-output/2018-10-16-arch-block-devs` should load the file `/resources/public/posts-output/2018-10-16-arch-block-devs.html`.

**Comment by niamu** [comment]
I think the problem here is that with this change cryogen now only works when publishing to GitHub Pages which serves pages with Jekyll and automatically serves the HTML file if the extension is there or not.

Whereas if you are using cryogen with Amazon S3 or another web server you now need to do an extra post-processing step of your own with cryogen's generated files to strip the extension and serve those files with the appropriate "text/html" MIME type for it to work properly.

**Comment by lacarmen** [comment]
Ah I see, I wasn't aware of that limitation. 

Do you have any suggestions that would allow us to support both approaches?

**Comment by niamu** [comment]
I think that since the recent change only works for GitHub Pages (as far as I know) and doesn't work in other static site hosting setups that it should be an additional configuration step separate from the `:clean-urls?` boolean. Perhaps something like `:clean-urls-trailing-slash?` could be used as an additional modifier with the note this feature is intended to work with GitHub Pages or otherwise requires additional post-processing steps.

I don't think Cryogen should attempt to generate files without the ".html" extension and then rely on the user to setup the proper MIME type when uploading the files to their web server as this gets rather messy and would be confusing in documentation. If someone would like to do the "even cleaner URLs" solution on a non-Github Pages setup I would assume they are probably savvy enough to script the necessary post-processing steps themselves.

**Comment by lacarmen** [comment]
@niamu some discussion happening on cryogen-project/cryogen#166

**Comment by lacarmen** [comment]
@willfurnass cryogen-core 0.1.68 has been pushed to clojars. Please check the [docs](http://cryogenweb.org/docs/configuration.html) for the new config options!

**Comment by willfurnass** [comment]
@lacarmen Wonderful - thanks for this!
