### ISSUE TITLE
Submodule conflict

### ISSUE THREAD

**Issue by mokagio** [cryogen-project/cryogen-core#18]
Hello guys, I've recently started learning Clojure and decided to checkout this Cryogen to setup a self reference blog.

I'm trying to automate my workflow, and I tried to setup the `gh-pages` branch into a git submodule. The point is avoiding to have to copy paste code between folders, and the idea is simple:

* Master ignores `public/my-project`
* `public/my-project` is added as a submodule pointing to the `gh-pages` branch
* Everytime the generated static code changes, those file get written only on the `public/my-project` folder, we can commit and push a new version to the `gh-pages`.

At the moment this doesn't work thought :disappointed: 

As I said I'm a Clojure rookie, but I think the issue is that the [`wipe-public-folder` function in `cryogen-core`](https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/io.clj#L43) deletes the `.git` folder in the submodule folder, so it doesn't know that it's a submodule and supposed to point to the `gh-pages` anymore. I might be wrong there, because I see that a filter is done based on `keep-files`, but nevertheless the `public/my-project` point to `gh-pages` when setup with `git submodule add -b gh-pages https://github.com/<username>/<project>.git public/my-project` and has a `.git` folder, and as soon as the local server regenerates the static content the `.git` folder is gone.

Unfortunately I cannot yet submit a PR with a fix for the issue, but I'm happy to provide more details. The project repo is https://github.com/mokagio/podcasts-notes, and I mainly followed [this guide](http://blog.revathskumar.com/2014/07/publish-github-pages-using-git-submodules.html) to understand how to setup the submodule workflow.

Thanks

**Comment by lacarmen** [comment]
When you have a blog-prefix and wipe-public-folder is called, [this](https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/io.clj#L45) line only iterates through all the files/dirs under `public` rather than `public/blog-prefix`.

You can fix your problem by simply changing the line that I referenced to look at the files under `(str public blog-prefix)` rather than just `public`. 

I won't be releasing this fix right away since this change presents some other problems but I think this will work for you in the meantime.

**Comment by mokagio** [comment]
Thanks for replying so quickly @lacarmen.

> You can fix your problem by simply changing the line that I referenced to look at the files under (str public blog-prefix) rather than just public.

I've had a look around and I can't find an easy way to just edit the `cryogen` project to point to my fork of `cryogen-core` with the fix. Keep in mind I'm a noob.

I guess I could create a `.jar` with the fix and replace it in the `~/.m2/resources/` folder, but this sounds like a lot of work...

Unless you can point me to a simpler solution I'll just script the copy-paste deployment process for the time being.

Cheers :beer:

**Comment by wjlroe** [comment]
@mokagio To use your own version of a library:

* Go to the directory of the library (such as `cryogen-core`)
* Edit the project name and version inside `project.clj` - for e.g. currently it says:

```clojure
(defproject cryogen-core "0.1.20"
```

For my changes and testing, I changed that to:

```clojure
(defproject org.clojars.wjlroe/cryogen-core "0.1.21-SNAPSHOT"
```

Basically I bumped the version and added `SNAPSHOT` which is the Clojure/Java way to indicate an unstable/not-released version (it possibly doesn't matter unless you plan to release your fork on clojars).

* Still in the cryogen-core directory, type `lein install` -- this packs it all up and puts the necessary files (a JAR file and a POM file) in your local maven repository so it can be picked up by leiningen (and, indeed anything Maven-based) without attempting to download it. Every time you change your fork of this library, you'll need to run `lein install` again and restart any processes running that use that library.

* Now go back to your blog and edit `project.clj` and substitute the dependency on `cryogen-core` to read:

```clojure
[cryogen-markdown "0.1.1" :exclusions [cryogen-core]]
[org.clojars.wjlroe/cryogen-core "0.1.21-SNAPSHOT"]
```

(adapt to match the name and version you chose in your fork of cryogen-core). Notice also it's necessary to tell Leiningen to ignore the dependency on cryogen-core from cryogen-markdown otherwise you'll get an older library being used. PROTIP: `lein deps :tree` in your blog directory will print out a tree of dependencies so you get a definitive answer for what libraries and versions are going to be used (it'll warn about conflicts but for the most part those warnings can be ignored).

If you do decide to push your fork to clojars, then it's a good idea to use your own groupId (that's the bit in my example that says `org.clojars.org.wjlroe`, and using something specific like that makes it clear it's a fork), then you will be able to run your blog code on any computer, not relying on manually installed libraries in your local maven repository.

I hope this helps - if there's anything unclear about this, I have the same username on twitter so feel free to ask.

**Comment by lacarmen** [comment]
@wjlroe :+1: 
I'd like to add that you should do this in your own cloned version of the cryogen-core library in case that wasn't clear. You don't need to mess around with the github forks :)

**Comment by johnmendonca** [comment]
@mokagio I was able to achieve what you were originally describing: keeping site output in gh-pages without copying files.  Using a git submodule or modifying core code should not be necessary.

The basic thing I have done is have the master branch at the project root with ```resources/public``` added to the .gitignore.  Then in the place of the public folder I clone the project again, rename it to 'public' and checkout gh-pages there.  I have written more detailed steps [on my cryoblog](http://john.mendonca.rocks/blog/2015-03-12-github-pages-folder-structure.html).

The .git folder being deleted should not be a problem using a recent version with the ```keep-files``` setting.

**Comment by mokagio** [comment]
Thanks guys. Sorry I've been unresposnive... Life!




I'll eventually go back on my setup and report back.




Cheers



—
Gio

**Comment by lacarmen** [comment]
So can we close this? :)

**Comment by mokagio** [comment]
Yep, that's fine by me :)

**Comment by lacarmen** [comment]
Excellent
