### ISSUE TITLE
Expose posts variable for the index page, posts preview

### ISSUE THREAD

**Issue by zshamrock** [cryogen-project/cryogen-core#28]
Right now, the base.html is assuming there is a one single post per page, with next/prev links. Would be nice to have `posts` variable available in base.html to support custom themes. Right now we have latest-posts, which is not enough.

Also, good to have a new config variable, `:posts-per-page 4`, or similar, for example, where we set how many post previews to display per page. And the posts filled in `posts` variable are changing dynamically every time we navigate next/prev, like, blog.com/p/2 (second page), and the variable saying total number of pages with posts based on the :posts-per-page size. And default blog.com or blog.com/index.html, assumes that the page number is 1.

It also requires to introduce extra `preview` field to the post variable itself, to display part of the post as preview (maybe even configurable from the post.md itself somehow, maybe adding a new param `:preview-lines 10`, for example).

And, extra one is to document all the variables available for the theme authors: like `latest-posts`, `navbar-pages` (why it is not called just `pages`?), etc., and the structure overview of all the availale fields of each map/variable, like `title`, `name`, for post, page, etc.

**Comment by lacarmen** [comment]
I really like this idea so I'm going to mark it as an enhancement and tackle it on a weekend. :)

And yes, with the introduction of the [config based themes](https://github.com/cryogen-project/cryogen-core/issues/12) I will definitely take a day to sit down and add some documentation about theming and all the variables you mentioned.

**Comment by zshamrock** [comment]
Nice, I might submit a PR, but will keep an eye on the progress in the meanwhile.
Yes, documentation is a little bit obsolete, because, there is a theme folder, but in the documentation it still referes to just html/layouts (in the lein template as well).

Thank you for the nice product.

**Comment by MicahElliott** [comment]
I just want to document here that a `<!-- more -->` comment is how this is usually done, and it’s very easy for the author to insert in Markdown or Asciidoc.

I have also noticed that some blogs style articles so that the first paragraph (or so) is in a slightly larger text ([example](http://alistapart.com/column/small-business-software-audits)). This gives the air of it being an “abstract”, and is even a convention that encourages writers to make sure they’re getting to the point in their leading sentences.

So it would be helpful to auto-class/-wrap the opening `<p>` or `<div>` (or however much comes before the `more` with an “abstract” or “intro” class.

**Comment by lacarmen** [comment]
I'm going to leave out the auto class-wrapping as not all users would want this as a default (myself included). If someone wanted to achieve that "abstract" look then they could wrap their first few paragraphs with a div inside their markup.

**Comment by lacarmen** [comment]
Just finished updating the core and template. New clojars build will be up tonight!
